server:
  port: 8003

spring:
  application:
    name: provide-data #\u5165\u9A7Beureka\u7684\u670D\u52A1\u540D\u79F0

eureka:
  client:
    service-url:
      defaultZone: http://eureka5001.com:5001/eureka