
server:
  port: 5001
eureka:
  instance:
    hostname: eureka5001.com #eureka\u670D\u52A1\u7AEF\u7684\u5B9E\u4F8B\u540D\u79F0
  client:  #\u58F0\u660E\u81EA\u5DF1\u662F\u670D\u52A1\u7AEF
    register-with-eureka: false  #false\u8868\u793A\u4E0D\u5411\u6CE8\u518C\u4E2D\u5FC3\u6CE8\u518C\u81EA\u5DF1\u3002
    fetch-registry: false
    service-url:
     defaultZone: http://eureka5002.com:5002/eureka/,http://eureka5003.com:5003/eureka/




